// CREATE THE BASIC MATH FUNCTIONS (ADD, SUBTRACT, MULTIPLY, DIVIDE)

function add(num1, num2) {
  return num1 + num2;
}

function subtract(num1, num2) {
  return (num1 = num2);
}

function multiply(num1, num2) {
  return num1 * num2;
}

function divide(num1, num2) {
  return num1 / num2;
}

// CREATE 3 VARIABLES, ONE FOR EACH PART OF THE OPERATION (NUM1, OPERATOR AND NUM2)

// CREATE THE FUNCTION OPERATE(NUM1, NUM2, OPERATOR){ ONE OF THE MATH FUNCITONS }

// CREATE THE FUNCTIONS THAT POPULATE THE DISPLAY WHEN A DIGIT IS CLICKED

// STORE THE CONTENT OF THE DISPLAY (THE NUMBER) IN A VARIABLE FOR USE IN NEXT STEP

// STORE THE FIRST AND SECOND NUMBERS INPUT BY THE USER, THEN CALL OPERATE() ON THEM WHEN THE USER PRESSES THE = BUTTON ACCORDING TO THE OPERATOR SELECTED BETWEEN THE NUMBERS. THEN UPDATE THE DISPLAY WITH THE RESULT

// ### GOTCHAS ###
